### ISSUE TITLE
Project ERROR: Could not resolve SDK Path 

### ISSUE THREAD

**Issue by lexieric** [Git-Jiro/homebrew-jiro#18]
$ brew install gridcoin
==> Installing gridcoin from git-jiro/jiro
==> Downloading https://github.com/gridcoin/Gridcoin-Research/archive/3.5.8.8b.t
Already downloaded: /Users/konstantinhaehnelt/Library/Caches/Homebrew/gridcoin-3.5.8.8b.tar.gz
==> qmake USE_UPNP=1
Last 15 lines from /Users/konstantinhaehnelt/Library/Logs/Homebrew/gridcoin/01.qmake:
2017-06-08 20:25:13 +0100

qmake
USE_UPNP=1

Project ERROR: Could not resolve SDK Path 

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/Git-Jiro/homebrew-jiro/issues

**Comment by coagmano** [comment]
Do you have qt installed and linked with homebrew? 
Because this formula uses a forked version of qt with the same name it can get confused about which to use

**Comment by ghost** [comment]
qt 4 is no longer supported by anyone to my knowledge. Delete all qt 4 and 5 versions on your system. Then "brew doctor" then "brew tap Git-Jiro/jiro" then " brew install git-jiro/jiro/gridcoin" and this will install all dependences for you. The finished app will be here for you when compiling is complete: /usr/local/Cellar/gridcoin

**Comment by lexieric** [comment]
Thank you both for your prompt response. Looks like I had both Qt 4 and Qt 5 installed. I followed Acey's instructions and am now letting it run, so far so good!!

**Comment by lexieric** [comment]
All working now. Thank you so much for the prompt and very helpful response!!!
