### ISSUE TITLE
Add to README : Can't install on macosx Sierra without Xcode first

### ISSUE THREAD

**Issue by christinasc** [Git-Jiro/homebrew-jiro#22]
Might want to put a mention somewhere in the README that Xcode is required as a prerequisite; especially if installing on non-developers' macOSX. 

See: https://stackoverflow.com/questions/41513456/qt-5-7-xcode-8-1-os-x-el-captain-could-not-resolve-sdk-path-for-macosx

https://stackoverflow.com/questions/26320677/error-could-not-resolve-sdk-path-for-macosx10-8%60

==> Installing gridcoin from git-jiro/jiro
==> Downloading https://github.com/gridcoin/Gridcoin-Research/archive/3.5.9.0a.tar.gz
Already downloaded: /Users/christina/Library/Caches/Homebrew/gridcoin-3.5.9.0a.tar.gz
==> qmake USE_UPNP=1 BOOST_INCLUDE_PATH=/usr/local/opt/boost/include BOOST_LIB_PATH=/usr/local/opt/boost/lib OPENSSL_INCLUDE_PATH=/usr/local/opt/o
Last 15 lines from /Users/christina/Library/Logs/Homebrew/gridcoin/01.qmake:
2017-06-26 18:28:28 +0800

qmake
USE_UPNP=1
BOOST_INCLUDE_PATH=/usr/local/opt/boost/include
BOOST_LIB_PATH=/usr/local/opt/boost/lib
OPENSSL_INCLUDE_PATH=/usr/local/opt/openssl/include
OPENSSL_LIB_PATH=/usr/local/opt/openssl/lib
BDB_INCLUDE_PATH=/usr/local/opt/berkeley-db@4/include
BDB_LIB_PATH=/usr/local/opt/berkeley-db@4/lib
MINIUPNPC_INCLUDE_PATH=/usr/local/opt/miniupnpc/include
MINIUPNPC_LIB_PATH=/usr/local/opt/miniupnpc/lib

Project ERROR: Could not resolve SDK Path for 'macosx10.12'

**Comment by Git-Jiro** [comment]
@christinasc I added a small paragraph as you suggested.

**Comment by christinasc** [comment]
One other thing -- the Command Line tools needs to be selected in Xcode or else it will still not be able to resolve the SDK Path. Might be helpful for non-developers to have a build option that doesn't require Xcode. 

![screen shot 2017-06-27 at 11 35 31 am](https://user-images.githubusercontent.com/1209633/27570474-0db378f6-5b31-11e7-973b-f3cc632494de.png)

**Comment by coagmano** [comment]
The Xcode setup is all part of installing homebrew, not specific to this formula

There's a bit of discussion on the [cryptocurrencytalk forum](https://cryptocurrencytalk.com/topic/13139-os-x-builds-feedback-bug-reporting/) about providing pre-built binaries to make things easier for non-developers
