### ISSUE TITLE
brew install --HEAD git-jiro/jiro/gridcoin fails on MacOS

### ISSUE THREAD

**Issue by infinitejones** [Git-Jiro/homebrew-jiro#24]
Looks like this is the problem:

`RCC: Error in 'src/qt/bitcoin.qrc': Cannot find file 'locale/bitcoin_zh_CN.qm'`

**Comment by coagmano** [comment]
Want to make an issue upstream?

**Comment by Git-Jiro** [comment]
I checked this right now. It is not reproducible anymore. Seems to be fixed upstream.
