### ISSUE TITLE
Hey There!

### ISSUE THREAD

**Issue by iFoggz** [Git-Jiro/homebrew-jiro#34]
Hey, I'm iFoggzx420 one of the gridcoin devs. would you be so kind as to join http://teamgridcoin.slack.com/ and sign up and join the channel "test". we would like to talk about your repo and see if we can find a way to make this work with Travis CI etc. thanks see you there.

EDIT:
I see you got Travis CI going with this. ill update them but we would like to make this build easier for future and also with new autotools that we will be using.

**Comment by ghost** [comment]
Hi Paul,

I am aceypilot and have joined slack test channel.

Regards,
Will



On Aug 29, 2017, at 4:25 PM, Paul Jensen <notifications@github.com> wrote:

Hey, I'm iFoggzx420 one of the gridcoin devs. would you be so kind as to join http://teamgridcoin.slack.com/ <http://teamgridcoin.slack.com/> and sign up and join the channel "test". we would like to talk about your repo and see if we can find a way to make this work with Travis CI etc. thanks see you there.

**Comment by Git-Jiro** [comment]
@Foggyx420 I am not yet very familiar with autotools, so in case something breaks I will definitely needs some help fixing things. See you on Slack!

**Comment by ghost** [comment]
Thank you Martin! I will communicate via Slack #test.

Regards,
Will



On Sep 2, 2017, at 6:51 PM, Martin Schimandl <notifications@github.com> wrote:

@Foggyx420 <https://github.com/foggyx420> I am not yet very familiar with autotools, so in case something breaks I will definitely needs some help fixing things. See you on Slack!
