### ISSUE TITLE
Advanced menu items are broken

### ISSUE THREAD

**Issue by ghost** [Git-Jiro/homebrew-jiro#35]
Jiro, I realize that you already know this, but thought I would give this as a reminder for when we are able to implement. 
Items "Rebuild Block Chain" and "Download Blocks/Upgrade functions under the "Advanced" menu in the upper task bar will not work yet, but will not affect day to day wallet operation.

I will put this in over on the gridcoinresearch side as well.

**Comment by Git-Jiro** [comment]
Thank you for the reminder Acey!

**Comment by ghost** [comment]
Grid coin core is addressing this issue.

**Comment by Git-Jiro** [comment]
Thanks for the update Acey!
