### ISSUE TITLE
make warnings...

### ISSUE THREAD

**Issue by zanuka** [Git-Jiro/homebrew-jiro#42]
seeing the following warnings on install via brew... 

`==> qmake USE_UPNP=1 BOOST_INCLUDE_PATH=/usr/local/opt/boost/include BOOST_LIB_PATH=/usr/local/opt/boost/lib OPENSSL_INC
==> make
Last 15 lines from /Users/method/Library/Logs/Homebrew/gridcoin/02.make:
/usr/local/opt/boost/include/boost/asio/ssl/impl/context.ipp:63:10: note: candidate constructor not viable: requires single argument 'm', but 2 arguments were provided
context::context(context::method m)
         ^
/usr/local/opt/boost/include/boost/asio/ssl/impl/context.ipp:326:10: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
context::context(context&& other)
         ^
/usr/local/opt/boost/include/boost/asio/ssl/context.hpp:36:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class context`

**Comment by Git-Jiro** [comment]
Thank you for reporting this.
It should be fixed now.

**Comment by ghost** [comment]
Thank you for repairing Jiro.

Regards,
William




On Jan 4, 2018, at 10:35 PM, Martin Schimandl <notifications@github.com> wrote:

Closed #42 <https://github.com/Git-Jiro/homebrew-jiro/issues/42>.

**Comment by zanuka** [comment]
quick fix, thanks!
