### ISSUE TITLE
brew install --devel Git-jiro/jiro/gridcoin    FAILURE

### ISSUE THREAD

**Issue by ghost** [Git-Jiro/homebrew-jiro#43]
HI JIRO!
I'm unable to compile the Staging Branch as requested by @ravon.  If we can't fix this, then the new pending 3.7 revision will be broken when it is merged with master. This are the errors I get. You have time to repair this please?

brew install --devel Git-jiro/jiro/gridcoin
==> Installing gridcoin from git-jiro/jiro
==> Cloning https://github.com/gridcoin/Gridcoin-Research.git
Updating /Users/william/Library/Caches/Homebrew/gridcoin--git
==> Checking out branch staging
==> Patching
patching file gridcoinresearch.pro
patching file src/rpcblockchain.cpp
Hunk #1 succeeded at 22 with fuzz 2 (offset 4 lines).
patching file src/rpcrawtransaction.cpp
Hunk #1 FAILED at 75.
Hunk #2 FAILED at 103.
2 out of 2 hunks FAILED -- saving rejects to file src/rpcrawtransaction.cpp.rej
patching file src/rpcwallet.cpp
Hunk #1 succeeded at 1061 (offset -1 lines).
Error: Failure while executing: patch -g 0 -f -p1

**Comment by Git-Jiro** [comment]
Hi Acey,
thank you for reporting this.
Should be fixed now.

**Comment by ghost** [comment]
Thank you Martin! It works great!
Regards,
William




On Jan 5, 2018, at 8:39 PM, Martin Schimandl <notifications@github.com> wrote:

Closed #43 <https://github.com/Git-Jiro/homebrew-jiro/issues/43>.
