### ISSUE TITLE
New version 3.7.0.0 Broken

### ISSUE THREAD

**Issue by ghost** [Git-Jiro/homebrew-jiro#44]
Hi Jiro,

I tried what @ravon said to do to repair this, but it does not work. He says the patches are no longer required, and to make without them. So we have a new mandatory version 3.7.0.0, but your patch is broken again. Auto Tools is supposed to make it in the next release 3.7.1.0, which works great. But for now, we have no new MacOS app for this new version 3.7.0.0.

Thanks for anything that you have time to do.

~Acey

**Comment by Git-Jiro** [comment]
No Problem, I will take a look and find out how to fix it.

**Comment by Git-Jiro** [comment]
Hi Acey, fortunately this was an easy fix. Just a small subset of the patches had to be removed as you said.

**Comment by ghost** [comment]
Nice work! Thank you Jiro!

Regards,
William




On Jan 11, 2018, at 5:21 AM, Martin Schimandl <notifications@github.com> wrote:

Closed #44 <https://github.com/Git-Jiro/homebrew-jiro/issues/44>.
