### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by ghost** [Git-Jiro/homebrew-jiro#48]
Hi, spoke to @caraka and he said they want the QR code working. But we must use flags in your patch to compile the QR into working condition. He also said he always uses these flags on production:
Here is his gui call in debian:  qmake gridcoinresearch.pro USE_QRCODE=1 USE_UPNP=1 NO_UPGRADE=1

The auto tools is still broken for us due to some Windows issues.

**Comment by Git-Jiro** [comment]
Thank you for reporting this. It is fixed now
