### ISSUE TITLE
Dev and Staging will not compile. 

### ISSUE THREAD

**Issue by ghost** [Git-Jiro/homebrew-jiro#52]
Although production works, Dev and Staging compiles are stuck in endless loop.

**Comment by Git-Jiro** [comment]
I will take a look at those as well.

**Comment by Git-Jiro** [comment]
The staging branch `brew install gridcoin --devel` worked for me

**Comment by Git-Jiro** [comment]
I can reproduce the endless loop issue on the development branch.

**Comment by ghost** [comment]
OK, I had the endless loop on Dev branch today, did not try Staging (---devel) since the version upgrade, so assumed it to still be true. I retried staging and indeed it works. Thank you.

**Comment by ghost** [comment]
Hi Jiro,

"brew install --HEAD Git-jiro/jiro/gridcoin" Is still in loop. Is this something that can be fixed from our side?

**Comment by Git-Jiro** [comment]
I have still no idea what causes this loop. Therefore I am not able to help with fixing it.

**Comment by ghost** [comment]
It’s my guess that auto tools is causing this, because of “make”.

 

Regards,

William

**Comment by ghost** [comment]
Staging is broken again.

patching file src/rpcwallet.cpp
Hunk #1 FAILED at 1062.
1 out of 1 hunk FAILED -- saving rejects to file src/rpcwallet.cpp.rej
Error: Failure while executing: patch -g 0 -f -p1

**Comment by Git-Jiro** [comment]
OK, I will have a look!

**Comment by Git-Jiro** [comment]
The development build works again now!
I changed from the qmake based build to the autotools based build.

**Comment by ghost** [comment]
Very cool. This is the way to go. 
		

		Regards,
William
	_____________________________

**Comment by ghost** [comment]
How about staging? It is not auto tools yet. Staging was not compiling this morning. 
		
		

		Regards,
William
	




On Sun, Apr 8, 2018 at 5:52 PM +0900, "William Keene" <wkeene101@gmail.com> wrote:













	
		
		
	
		
		Very cool. This is the way to go. 
		

		Regards,
William
	_____________________________

**Comment by Git-Jiro** [comment]
Oh sorry, I mixed up the branches a little:
I tested with `brew install --devel gridcoin`, which is the staging branch. This works now.

I briefly checked `brew install --HEAD grirdcoin`, which is the development branch. This is not working now.

**Comment by ghost** [comment]
Yes the terms are indeed counter intuitive. No issue. So you fixed the HEAD or development branch it appears.  Correct?
		
		

		Regards,
William
	




On Sun, Apr 8, 2018 at 6:03 PM +0900, "Martin Schimandl" <notifications@github.com> wrote:












Oh sorry, I mixed up the branches a little:

I tested with brew install --devel gridcoin, which is the staging branch. This works now.


I briefly checked brew install --HEAD grirdcoin, which is the development branch. This is not working now.

**Comment by ghost** [comment]
I am away from laptop by the way. 
		
		

		Regards,
William
	




On Sun, Apr 8, 2018 at 6:03 PM +0900, "Martin Schimandl" <notifications@github.com> wrote:












Oh sorry, I mixed up the branches a little:

I tested with brew install --devel gridcoin, which is the staging branch. This works now.


I briefly checked brew install --HEAD grirdcoin, which is the development branch. This is not working now.

**Comment by Git-Jiro** [comment]
I left the master branch as is, which is the stable/release branch in Gridcoin.
I fixed the staging branch, because this is becoming the master/stable/release branch eventually.
I ignored the development branch, because it is not important for regular users
