### ISSUE TITLE
Virus in your latest build

### ISSUE THREAD

**Issue by Pwrdude** [Git-Jiro/homebrew-jiro#61]
Total Protection picked up the Artemis virus in your latest build, need to check it out...

**Comment by ghost** [comment]
No issues with the app here on my system. You may have false positive Pwrdude.

**Comment by Pwrdude** [comment]
Problem solved with McAfee, it was indeed an FP.

**Comment by ghost** [comment]
Thanks for checking this Pwrdude.

**Comment by Dr-Infinity** [comment]
FWIW, had same report from Intego's VirusBarrier, made support request to Intego saying I thought it FP.
Ran all available versions of  gridcoinresearch.dmg downloads on GitHub against VirusBarrier and ALL had positive scan so wasn't just latest build.
Updated definitions from Intego no longer reporting installer as virus laden.

**Comment by ghost** [comment]
Thank you for your good work Dr.
