### ISSUE TITLE
Auto tools is now available on master branch

### ISSUE THREAD

**Issue by ghost** [Git-Jiro/homebrew-jiro#62]
Hi Jiro,

Just used auto tools to compile GRC master branch. What now?

The Jiro patch shows: Hunk #1 FAILED at 1062.
1 out of 1 hunk FAILED -- saving rejects to file src/rpcwallet.cpp.rej
Error: Failure while executing: patch -g 0 -f -p1

**Comment by Git-Jiro** [comment]
Hi! I will have a look at this!

**Comment by Git-Jiro** [comment]
Hi Acey! It's fixed now! Master is building with autotools!

**Comment by ghost** [comment]
Thanks!
