### ISSUE TITLE
4.0.1: Infected executable

### ISSUE THREAD

**Issue by chuckcoleman** [Git-Jiro/homebrew-jiro#71]
This just popped up from my antivirus.
![screen shot 2019-01-01 at 10 51 15 am](https://user-images.githubusercontent.com/25271226/50574287-5d788f80-0db3-11e9-982b-2ed475cf3ed1.png)

**Comment by Git-Jiro** [comment]
Yes, I have had a similar report from someone else with another version of the Gridcoin-Client and another Anti-Virus Software.
The message is not completely wrong though: Gridcoin DOES have some shared origins with BitCoin. I guess that is the reason why these false alarms will keep appearing from time to time. Unfortunately I have no idea what could be done against those false alarms.

**Comment by chuckcoleman** [comment]
Better a false positive than a false negative. I suspect there's some shared binary code that is the BTC miner's signature in the scanners.
    On Wednesday, January 2, 2019, 12:01:40 PM EST, Martin Schimandl <notifications@github.com> wrote:  
 
 
Yes, I have had a similar report from someone else with another version of the Gridcoin-Client and another Anti-Virus Software.
The message is not completely wrong though: Gridcoin DOES have some shared origins with BitCoin. I guess that is the reason why these false alarms will keep appearing from time to time. Unfortunately I have no idea what could be done against those false alarms.

**Comment by chuckcoleman** [comment]
I just realized that I can't run Gridcoin because of this problem.  I downloaded the dmg and avast antivirus blocked installation. :-(

**Comment by chuckcoleman** [comment]
I lost access to Gridcoin, so I had to turn off the real-time file scanning and exclude it from system scans.  Now, it's running fine.

A fix may be to put some useless code in the shared section(s). Something like incrementing a superfluous variable.

**Comment by Git-Jiro** [comment]
Unfortunately adding some superfluous code won't help. You never know what kind of signatures all the different antivirus vendors are going to use.
