### ISSUE TITLE
4.0.1 crashes on launch on High Sierra

### ISSUE THREAD

**Issue by barton2526** [Git-Jiro/homebrew-jiro#72]
Below is a report forwarded from user "Sea Mac" on Discord (he doesn't have a Github account):

I can't get the Gridcoin Research App to launch.
It throws an Error:

> 
> Time Awake Since Boot: 10000 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
> Exception Codes:       0x0000000000000001, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Signal:    Illegal instruction: 4
> Termination Reason:    Namespace SIGNAL, Code 0x4
> Terminating Process:   exc handler [0]
> 
> Application Specific Information:
> /Applications/gridcoinresearch.app/Contents/MacOS/gridcoinresearch

Starting from scratch ... can't install Leisure Client.

> Mar 18 14:23:37 Triple-Time com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000018.gridcoinresearch[5675]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0] Mar 18 14:23:37 Triple-Time com.apple.xpc.launchd[1] (com.apple.ReportCrash[5677]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash

Illegal Instruction error. I NEVER got this thing to launch. No Account/No Preferences/No blockchain/No nothing.

> Crashed Thread:        4  Dispatch queue: Email credential verification queue :: NSOperation 0x7ff7c9134fc0 (QOS: DEFAULT)
> 
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Application Specific Information:
>  Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: ' -[NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
> terminating with uncaught exception of type NSException
> abort() called
> 
> Application Specific Backtrace 1:
> 0   CoreFoundation                      0x00007fff8659050b exceptionPreprocess + 171
> 1   libobjc.A.dylib                     0x00007fff9b9861da

It's a launch failure - it happens with 3.7.16_macOS_10.12 also

**Comment by barton2526** [comment]
Attached are the relevant log files:

[gridcoinresearch_2019-03-18-142338_Triple-Time_crash.rtfd.zip](https://github.com/Git-Jiro/homebrew-jiro/files/2980682/gridcoinresearch_2019-03-18-142338_Triple-Time_crash.rtfd.zip)

**Comment by Git-Jiro** [comment]
Thanks, I will have a look at this.
I have a High Sierra VM to try to reproduce the issue.

**Comment by Git-Jiro** [comment]
I failed to reproduce the issue with the application from the DMG file.
@barton2526 maybe you could suggest/explain to "Sea Mac" how to use Homebrew directly to install Gridcoin that way? Usually the self-compiled version works when the DMG version does not.
