### ISSUE TITLE
does not build with boost >= 1.70

### ISSUE THREAD

**Issue by wilkart** [Git-Jiro/homebrew-jiro#73]
Currently the latest boost is 1.70.0 and it does not build anymore.
I solved this by changing to 
`depends_on "boost@1.60"` in gridcoin.rb
and
`brew link boost@1.60 --force`

**Comment by Git-Jiro** [comment]
Thanks, I will include this change in the next release

**Comment by wilkart** [comment]
thanks for quick reply, maybe you could check the #packaging channel on TeamGridcoin slack and as we could maybe discuss if it does make sense to keep this formula like this. Because the Cask works great and Homebrew team advices do not deliver applications this way. 
We could switch this to command line only gridcoinresearchd only perhaps.
I am curious about your opinion.

**Comment by Git-Jiro** [comment]
I agree, deploying via this formula is not recommended for users.
However the DMG file from the Travis-CI build for this repository is what gets packaged into the cask right now.

**Comment by jamescowens** [comment]
This is also being tracked by https://github.com/gridcoin-community/Gridcoin-Research/issues/1498.

We need to refactor the net code to provide compatibility with 1.70+. It will probably be a while for that. Can we force the use of <1.70 until then without losing the GUI version?

**Comment by Git-Jiro** [comment]
Problem solved by pinning boost to version 1.60 as suggested by @wilkart
