### ISSUE TITLE
Gridcoin Wallet do not work under Big Sur

### ISSUE THREAD

**Issue by Shorty68DE** [Git-Jiro/homebrew-jiro#85]
Gridcoin Wallet do not work under Big Sur. The app do start but now window are going visible. The task manager says that Gridcoin do not response.

**Comment by Git-Jiro** [comment]
Hi!
I am able to reproduce this issue in a VM with macOS Big Sur.
Unfortunately at the moment I have no idea what the problem actually is.

**Comment by Git-Jiro** [comment]
Hi!
This issue only seems to affect the DMG file.
The regular Homebrew installation seems to work fine.

**Comment by Shorty68DE** [comment]
How can I make a "Homebrew"-Installation?

**Comment by Git-Jiro** [comment]
Step 1 would be to install the Homebrew Package Manager for mac OS as explained here:
https://brew.sh/

Then you can add a so called "TAP" with the Gridcoin installation instructions:
> brew tap Git-Jiro/jiro

And finally you can run
> brew install gridcoin

and it should compile and install Gridcoin for macOS on your local machine

**Comment by Shorty68DE** [comment]
Thank you very much for your help!!!! Now, the Gridcoin Wallet works with the brew installion!!!! Great!!!!

**Comment by Git-Jiro** [comment]
Glad I could help!
